define({ root: //begin v1.x content
	({
		"click-to-load-message": "Click to load more items",
		"loading-message": "Loading more items...",
		"default-click-to-load-message": "Click to load ${pageLength} more items",
		"default-loading-message": "Loading ${pageLength} more items..."
	})
//end v1.x content
	,
	"zh": false,
	"zh-tw": false,
	"uk": false,
	"tr": false,
	"th": false,
	"sv": false,
	"sl": false,
	"sk": false,
	"ru": false,
	"ro": false,
	"pt": false,
	"pt-pt": false,
	"pl": false,
	"nl": false,
	"nb": false,
	"ko": false,
	"kk": false,
	"ja": false,
	"it": false,
	"hu": false,
	"hr": false,
	"he": false,
	"fr": false,
	"fi": false,
	"es": false,
	"el": false,
	"de": false,
	"da": false,
	"cs": false,
	"ca": false,
	"bg": false,
	"az": false,
	"ar": false
});
